apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.microserviceName }}-service"
  labels:
    app.kubernetes.io/name: {{ .Values.microserviceName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Values.microserviceName }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
