apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: spoontab-host
  namespace: emissary
spec:
  hostname: spoontab.com
  tlsSecret:
    name: spoontab-tls
  acmeProvider:
    email: sneha.basnet2@gmail.com
    