
services:
  mongodb:
    image: mongo:7
    container_name: restaurant-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: restaurant-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    hostname: rabbitmq

volumes:
  mongo_data:
  rabbitmq_data: