
services:
  mongodb:
    image: mongo:7
    container_name: restaurant-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  postgres:
    image: postgres:15
    container_name: identity-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: identity_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rest@urant12
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    container_name: restaurant-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    hostname: rabbitmq
    
  seq:
    image: datalust/seq
    container_name: restaurant-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - 5341:80
    volumes:
      - seq_data:/data

volumes:
  mongo_data:
  rabbitmq_data:
  seq_data:
  postgres-data: