apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}
data:
  config.js: |
    {{- range $entry := .Values.configValues }}
      window.{{ $entry.key }} = {{ $entry.value }};
    {{- end }}
