global:
  scrape_interval: 15s

scrape_configs:
  - job_name: identity
    static_configs:
      - targets: ["host.docker.internal:5265"]

  - job_name: catalog
    static_configs:
      - targets: ["host.docker.internal:5062"]

  - job_name: order
    static_configs:
      - targets: ["host.docker.internal:5236"]

  - job_name: payment
    static_configs:
      - targets: ["host.docker.internal:5238"]
