name: Frontend CI (services/frontend)

on:
  push:
    branches: [ dev, main ]
    paths:
      - 'services/frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ dev, main ]
    paths:
      - 'services/frontend/**'
      - '.github/workflows/frontend-ci.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: services/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --fund=false

      - name: Type check & build
        run: npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: services/frontend/dist

  docker-smoke:
    name: Docker Build (Smoke)
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: services/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: services/frontend
          load: true
          tags: pos-frontend:ci

      - name: Run container (smoke)
        run: |
          docker run -d -p 8080:80 --name pos-frontend-ci pos-frontend:ci
          sleep 3
          curl -fS http://localhost:8080/ > /dev/null
          curl -fS http://localhost:8080/config.js > /dev/null
          docker logs pos-frontend-ci --tail=50 || true
          docker rm -f pos-frontend-ci
