name: Publish Messaging.Contracts

# Tag pattern: messaging.contracts-v1.2.3
on:
  push:
    branches: [dev, main]
    paths:
      - 'shared/Messaging.Contracts/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write


env:
  PACKAGE_ID: Messaging.Contracts
  PROJECT_PATH: shared/Messaging.Contracts/Messaging.Contracts.csproj

concurrency:
  group: publish-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  pack-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          source-url: "https://nuget.pkg.github.com/${{github.repository_owner}}/index.json"
        env: 
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Pack
        run: |
         dotnet pack ${{ env.PROJECT_PATH }} --configuration Release \
         -p:RepositoryUrl="https://github.com/${{github.repository_owner}}/restaurant.pos" \
         -o Packages

      - name: Publish
        run: |
          dotnet nuget push Packages/*.nupkg \
            --source "https://nuget.pkg.github.com/${{github.repository_owner}}/index.json" \
            --api-key "${{ secrets.GITHUB_TOKEN }}" \
            --skip-duplicate
