name: Publish Tenant.Domain

# Tag pattern: tenant.domain-v1.2.3
on:
  push:
    tags:
      - 'tenant.domain-v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic version (MAJOR.MINOR.PATCH) e.g. 1.0.0'
        required: true
        default: '1.0.0'

permissions:
  contents: read
  packages: write

env:
  PACKAGE_ID: Tenant.Domain
  PROJECT_PATH: shared/tenant.domain/Tenant.Domain.csproj

concurrency:
  group: publish-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  generate-version:
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.version.outputs.version }}
    steps:
      - name: Resolve version
        id: version
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
            RAW_TAG="${GITHUB_REF_NAME}"
            VERSION="${RAW_TAG#tenant.domain-v}"
          else
            VERSION='${{ inputs.version }}'
          fi
          if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version '$VERSION'" >&2
            exit 1
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  pack-and-push:
    needs: generate-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          source-url: "https://nuget.pkg.github.com/${{github.repository_owner}}/index.json"
        env: 
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Pack
        run: |
         dotnet pack ${{ env.PROJECT_PATH }} --configuration Release \
         -p:PackageVersion=${{ needs.generate-version.outputs.new-version}} \
         -p:RepositoryUrl="https://github.com/${{github.repository_owner}}/restaurant.pos" \
         -o Packages

      - name: Publish
        run: dotnet nuget push Packages/*.nupkg
